name: Upstream Sync

permissions:
  contents: write
  issues: write
  actions: write

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}   # 这一步也用 PAT

      - name: Clean issue notice
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          labels: '🚨 Sync Fail'

      - name: Debug PAT_TOKEN
        run: |
          if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
            echo "❌ PAT_TOKEN is EMPTY"
            exit 1
          else
            echo "✅ PAT_TOKEN is set"
          fi
        
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: lobehub/lobe-chat
          upstream_sync_branch: main
          source_repo_token: ${{ secrets.PAT_TOKEN }}  # 新增，拉 upstream 用
          target_sync_branch: main
          target_repo_token: ${{ secrets.PAT_TOKEN }}  # 推送 fork 用
          test_mode: false

      - name: Sync check
        if: failure()
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-issue'
          title: '🚨 同步失败 | Sync Fail'
          labels: '🚨 Sync Fail'
          body: |
            上游仓库 workflow 文件有改动，需要你手动同步一次。
